---
api:
  bind: :8080
db:
#  conn_string: "host=localhost port=15432 user=user_db dbname=users_db sslmode=disable" # use it for the local development
  conn_string: "host=users_db port=5432 user=user_db dbname=users_db sslmode=disable"
  max_open_conns: 100
  conn_max_lifetime: 60s
  migration_dir_path: "./sql-migrations"
  migration_table: "migrations"
