version: "3.9"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "users_db"
    networks:
      - default
    environment:
      - OTEL_SERVICE_NAME=users-manager
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger-tracing:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
  users_db:
    image: "postgres:15.13"
    ports:
      - "15432:5432"
    networks:
      - default
    hostname: users_db
    command:
      - --max_prepared_transactions=100
    environment:
      - POSTGRES_USER=user_db
      - POSTGRES_DB=users_db
      - POSTGRES_HOST_AUTH_METHOD=trust
  tracing:
    image: "jaegertracing/all-in-one:1.69.0"
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - default
    hostname: jaeger-tracing
