name: build

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]

env:
  GOLANG_VERSION: '1.18'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: test
        run: make test

      - name: Build
        run: make docker-build

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3


